"""The committed proof reports under artifacts/native-bog/ match a fresh run."""

from __future__ import annotations

import importlib.util
import json
import sys
from pathlib import Path

import pytest

from bactalk.library_demo import lbnl_multizone_ahu_demo_job, lbnl_vav_reheat_demo_job
from bactalk.niagara.mutate import OPERATORS

pytestmark = [pytest.mark.native_bog]

ROOT = Path(__file__).resolve().parents[1]
ARTIFACTS = ROOT / "artifacts" / "native-bog"


def _load(name: str):
    spec = importlib.util.spec_from_file_location(name, ROOT / "scripts" / f"{name}.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


proofs = _load("native_bog_proofs")


@pytest.mark.parametrize("proof", ["d1", "d2"])
def test_committed_structural_proofs_match_a_fresh_run(proof: str) -> None:
    path = ARTIFACTS / f"{proof}-tier1.json"
    assert path.is_file(), f"run scripts/native_bog_proofs.py --only {proof}"
    fresh = proofs.render(proof)
    assert path.read_text(encoding="utf-8") == fresh, f"{path} drifted; regenerate it"
    assert json.loads(fresh)["passed"] is True


def test_committed_d3_report_is_green_for_every_tier_one_case() -> None:
    """The D3 report is regenerated by scripts/native_bog_proofs.py; the differential
    itself runs in tests/test_native_bog_differential.py. Here the committed copy must
    be green and name every retained case."""

    report = json.loads((ARTIFACTS / "d3-tier1.json").read_text(encoding="utf-8"))
    assert report["schema"] == "bactalk.native-bog-proof/d3/v1" and report["passed"] is True
    by_equipment = {item["equipment"]: item for item in report["items"]}
    for build in (lbnl_vav_reheat_demo_job, lbnl_multizone_ahu_demo_job):
        job = build()
        item = by_equipment[job.equipment_name]
        assert item["reference"] == "Open Control Engine"
        for leg in ("default_policy", "coarse_module_tick"):
            assert item[leg]["passed"] is True
            assert [case["name"] for case in item[leg]["cases"]] == [
                case.name for case in job.acceptance_tests
            ]
            assert all(
                case["legs"] == ["interpreter", "reference", "shadow"]
                for case in item[leg]["cases"]
            )


def test_committed_d4_report_records_the_measured_catch_rates() -> None:
    """The D4 report is regenerated by scripts/native_bog_proofs.py --only d4 (slow:
    200 mutants per controller through four oracles). The committed copy must name
    both controllers, state its sample, and report the target honestly: `passed`
    is only true when every controller meets it (docs/decisions/009)."""

    path = ARTIFACTS / "d4-tier1.json"
    assert path.is_file(), "run scripts/native_bog_proofs.py --only d4"
    report = json.loads(path.read_text(encoding="utf-8"))
    assert report["schema"] == "bactalk.native-bog-proof/d4/v1"
    assert report["oracles"] == ["validator", "loader", "suite", "differential"]
    by_equipment = {item["equipment"]: item for item in report["items"]}
    assert set(by_equipment) == {"VAV_21", "AHU_1"}
    for item in by_equipment.values():
        assert item["sample"] == proofs.MUTATION_SAMPLE
        assert item["seed"] == proofs.MUTATION_SEED
        assert item["mutants_generated"] >= item["sample"]
        assert item["caught"] + len(item["survivors"]) == item["sample"]
        assert item["catch_rate"] == round(item["caught"] / item["sample"], 4)
        assert item["target"] == proofs.MUTATION_TARGET
        assert item["target_met"] == (item["catch_rate"] >= item["target"])
        assert set(item["by_operator"]) <= set(OPERATORS)
        for survivor in item["survivors"]:
            assert survivor["caught_by"] is None
    assert report["passed"] == all(item["target_met"] for item in report["items"])
    # Neither Tier 1 suite meets the target yet (docs/decisions/009, STATUS.md N8
    # findings): the report must say so rather than be regenerated into silence.
    assert report["passed"] is False
