"""The Niagara type and slot catalog (GOAL-NATIVE-BOG.md N1).

``catalog/harvested.json`` is generated by ``scripts/harvest_niagara_catalog.py``
from real ``.bog`` files and pybog's slot tables; ``catalog/supplement.json`` is
hand-written from Tridium documentation and every entry in it is ``doc-only``.
This module merges the two into an immutable :class:`NiagaraCatalog` and resolves
the ``symbol:Name`` spellings a ``.bog`` file uses to the ``module:Name`` keys
the catalog is indexed by.
"""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping
from dataclasses import dataclass, field
from functools import cache
from importlib import resources
from types import MappingProxyType

HARVESTED_ORIGIN = "harvested"
PYBOG_ORIGIN = "pybog"
DOC_ONLY_ORIGIN = "doc-only"

# Value types that carry a signal, and the kind the validator matches across links.
DATA_KINDS: Mapping[str, str] = MappingProxyType(
    {
        "baja:StatusNumeric": "numeric",
        "baja:StatusBoolean": "boolean",
        "baja:StatusEnum": "enum",
        "baja:StatusString": "string",
        "baja:Double": "numeric",
        "baja:Float": "numeric",
        "baja:Integer": "numeric",
        "baja:Long": "numeric",
        "baja:Boolean": "boolean",
        "baja:String": "string",
        "baja:RelTime": "reltime",
        "baja:FrozenEnum": "enum",
    }
)


@dataclass(frozen=True)
class SlotSpec:
    name: str
    value_type: str | None
    data_kind: str | None
    direction: str | None
    origins: tuple[str, ...]
    slot_kind: str = "property"
    link_target_seen: int = 0
    link_source_seen: int = 0

    @property
    def doc_only(self) -> bool:
        return self.origins == (DOC_ONLY_ORIGIN,)


@dataclass(frozen=True)
class TypeSpec:
    type: str
    module: str
    name: str
    origin: str
    dynamic_slots: bool
    slots: Mapping[str, SlotSpec]
    sources: tuple[str, ...] = ()
    component_count: int = 0

    @property
    def doc_only(self) -> bool:
        return self.origin == DOC_ONLY_ORIGIN


@dataclass(frozen=True)
class NiagaraCatalog:
    schema: str
    types: Mapping[str, TypeSpec]
    symbols: Mapping[str, str]
    facet_keys: Mapping[str, tuple[str, ...]]
    sources: Mapping[str, Mapping[str, str]]
    extra: tuple[str, ...] = field(default_factory=tuple)

    def get(self, type_key: str) -> TypeSpec | None:
        return self.types.get(type_key)

    def __contains__(self, type_key: object) -> bool:
        return type_key in self.types

    def resolve(self, type_spec: str, modules: Mapping[str, str]) -> str | None:
        """Turn ``symbol:Name`` into ``module:Name`` using the file's declarations.

        A symbol the file has not declared falls back to the customary symbol
        table harvested from the corpus; an unknown symbol returns ``None``.
        """

        symbol, _, name = type_spec.partition(":")
        if not name:
            return None
        module = modules.get(symbol) or self.symbols.get(symbol)
        if module is None:
            return None
        return f"{module}:{name}"

    def with_types(self, extra: Iterable[TypeSpec]) -> NiagaraCatalog:
        """A catalog that also knows declared (for example ``bactalkG36``) types."""

        merged = dict(self.types)
        names = list(self.extra)
        for spec in extra:
            merged[spec.type] = spec
            names.append(spec.type)
        return NiagaraCatalog(
            schema=self.schema,
            types=MappingProxyType(merged),
            symbols=self.symbols,
            facet_keys=self.facet_keys,
            sources=self.sources,
            extra=tuple(names),
        )


def _slot_from_harvest(name: str, raw: Mapping[str, object]) -> SlotSpec:
    origins = tuple(
        PYBOG_ORIGIN if str(item).startswith("pybog") else str(item)
        for item in raw.get("origins", ())
    )
    direction = raw.get("pybog_direction")
    if direction is None:
        if int(raw.get("link_target", 0) or 0) > 0:
            direction = "input"
        elif int(raw.get("link_source", 0) or 0) > 0:
            direction = "output"
    value_type = raw.get("value_type")
    return SlotSpec(
        name=name,
        value_type=str(value_type) if value_type else None,
        data_kind=raw.get("data_kind") if isinstance(raw.get("data_kind"), str) else None,
        direction=str(direction) if direction else None,
        origins=origins or (HARVESTED_ORIGIN,),
        link_target_seen=int(raw.get("link_target", 0) or 0),
        link_source_seen=int(raw.get("link_source", 0) or 0),
    )


def _slot_from_supplement(name: str, raw: Mapping[str, object]) -> SlotSpec:
    value_type = raw.get("value_type")
    return SlotSpec(
        name=name,
        value_type=str(value_type) if value_type else None,
        data_kind=DATA_KINDS.get(str(value_type)) if value_type else None,
        direction=str(raw["direction"]) if raw.get("direction") else None,
        origins=(DOC_ONLY_ORIGIN,),
        slot_kind=str(raw.get("slot_kind", "property")),
    )


def _expand_ranges(entry: Mapping[str, object]) -> dict[str, Mapping[str, object]]:
    slots: dict[str, Mapping[str, object]] = {}
    for spec in entry.get("slot_ranges", ()):
        assert isinstance(spec, Mapping)
        prefix = str(spec["prefix"])
        common = {
            key: value
            for key, value in spec.items()
            if key not in {"prefix", "from", "to", "letters"}
        }
        if "letters" in spec:
            names = [f"{prefix}{letter}" for letter in str(spec["letters"])]
        else:
            names = [f"{prefix}{index}" for index in range(int(spec["from"]), int(spec["to"]) + 1)]
        for name in names:
            slots[name] = common
    explicit = entry.get("slots", {})
    assert isinstance(explicit, Mapping)
    slots.update(explicit)
    return slots


def _merge_slot(base: SlotSpec | None, doc: SlotSpec) -> SlotSpec:
    """A harvested slot keeps its evidence; the doc entry fills the gaps only."""

    if base is None:
        return doc
    origins = base.origins if base.value_type else (*base.origins, DOC_ONLY_ORIGIN)
    return SlotSpec(
        name=base.name,
        value_type=base.value_type or doc.value_type,
        data_kind=base.data_kind or doc.data_kind,
        direction=base.direction or doc.direction,
        origins=origins,
        slot_kind=doc.slot_kind if doc.slot_kind != "property" else base.slot_kind,
        link_target_seen=base.link_target_seen,
        link_source_seen=base.link_source_seen,
    )


def build_catalog(
    harvested: Mapping[str, object], supplement: Mapping[str, object]
) -> NiagaraCatalog:
    types: dict[str, TypeSpec] = {}
    raw_types = harvested["types"]
    assert isinstance(raw_types, Mapping)
    for key, raw in raw_types.items():
        assert isinstance(raw, Mapping)
        raw_slots = raw["slots"]
        assert isinstance(raw_slots, Mapping)
        slots = {name: _slot_from_harvest(name, item) for name, item in raw_slots.items()}
        origin = str(raw.get("origin", HARVESTED_ORIGIN))
        types[key] = TypeSpec(
            type=key,
            module=str(raw["module"]),
            name=str(raw["name"]),
            origin=origin,
            dynamic_slots=bool(raw.get("dynamic_slots", False)),
            slots=MappingProxyType(slots),
            sources=tuple(str(item) for item in raw.get("sources", ())),
            component_count=int(raw.get("component_count", 0) or 0),
        )
    doc_types = supplement["types"]
    assert isinstance(doc_types, Mapping)
    for key, entry in doc_types.items():
        assert isinstance(entry, Mapping)
        base = types.get(key)
        slots = dict(base.slots) if base is not None else {}
        for name, raw in _expand_ranges(entry).items():
            slots[name] = _merge_slot(slots.get(name), _slot_from_supplement(name, raw))
        module, _, name = key.partition(":")
        types[key] = TypeSpec(
            type=key,
            module=base.module if base else module,
            name=base.name if base else name,
            origin=base.origin if base else DOC_ONLY_ORIGIN,
            dynamic_slots=base.dynamic_slots if base else False,
            slots=MappingProxyType(slots),
            sources=base.sources if base else (),
            component_count=base.component_count if base else 0,
        )
    modules = harvested.get("modules", {})
    assert isinstance(modules, Mapping)
    symbols = {
        symbol: max(counts.items(), key=lambda item: item[1])[0]
        for symbol, counts in modules.items()
        if isinstance(counts, Mapping) and counts
    }
    facet_keys = harvested.get("facet_keys", {})
    assert isinstance(facet_keys, Mapping)
    sources = harvested.get("sources", {})
    assert isinstance(sources, Mapping)
    return NiagaraCatalog(
        schema=str(harvested["schema"]),
        types=MappingProxyType(dict(sorted(types.items()))),
        symbols=MappingProxyType(symbols),
        facet_keys=MappingProxyType(
            {key: tuple(sorted(value)) for key, value in facet_keys.items()}
        ),
        sources=MappingProxyType({key: dict(value) for key, value in sources.items()}),
    )


def _load_json(name: str) -> Mapping[str, object]:
    package = resources.files("bactalk.niagara") / "catalog" / name
    return json.loads(package.read_text(encoding="utf-8"))


@cache
def load_catalog() -> NiagaraCatalog:
    """The packaged catalog; cached for the life of the process."""

    return build_catalog(_load_json("harvested.json"), _load_json("supplement.json"))
