"""The readable test plan: requirement → scenarios → expected result → pass/fail,
with the mutation and invariant results. It joins the approval digest and doubles
as the commissioning functional test plan."""

from __future__ import annotations

from typing import Any

from bactalk.protocol.requirements import (
    Outcome,
    RequirementApproval,
    RequirementSet,
    approval_status,
    canonical_digest,
)
from bactalk.protocol.test_author import TestPlan


def _outcome_text(outcome: Outcome) -> str:
    if outcome.operator == "between":
        return f"{outcome.point} in [{outcome.value:g}, {outcome.upper:g}]"
    symbol = {"eq": "=", "ne": "≠", "gt": ">", "gte": "≥", "lt": "<", "lte": "≤"}[outcome.operator]
    value = outcome.value if isinstance(outcome.value, bool) else f"{outcome.value:g}"
    tolerance = f" ±{outcome.tolerance:g}" if outcome.tolerance else ""
    return f"{outcome.point} {symbol} {value}{tolerance}"


def _expected_text(scenario_case: Any) -> str:
    parts: list[str] = []
    for phase in scenario_case.timeline:
        if not phase.expectations:
            continue
        expectations = ", ".join(
            f"{e.target} {e.operator.value} {e.value}"
            + (f"..{e.upper}" if e.upper is not None else "")
            for e in phase.expectations
        )
        parts.append(f"{phase.name}: {expectations}")
    return "; ".join(parts)


def approval_digest(
    requirements: RequirementSet, plan: TestPlan, adequacy: dict[str, Any] | None
) -> str:
    """One digest over the requirement set, the plan and the adequacy result."""

    return canonical_digest(
        {
            "requirements_digest": requirements.digest(),
            "plan_digest": plan.digest(),
            "adequacy_digest": canonical_digest(adequacy) if adequacy is not None else None,
        }
    )


def render_test_plan(
    requirements: RequirementSet,
    plan: TestPlan,
    adequacy: dict[str, Any] | None = None,
    approval: RequirementApproval | None = None,
) -> str:
    """Markdown for the web app, the approval bundle and `docs/test-plans/`."""

    status = approval_status(requirements, approval)
    results: dict[str, dict[str, Any]] = {}
    if adequacy is not None:
        results = {item["name"]: item for item in adequacy["suite"]["scenarios"]}
    lines = [
        f"# Test plan: {requirements.title}",
        "",
        f"Sequence `{requirements.sequence_id}` (Tier {requirements.tier}), requirements "
        f"version {requirements.version}, digest `{requirements.digest()}`.",
        f"Requirements approval (Gate G-ENG): **{status}**"
        + (
            f" by {approval.reviewer} at {approval.approved_at.isoformat()}"
            if approval and status == "approved"
            else ""
        )
        + ".",
        f"Test plan digest `{plan.digest()}`, generated by `{plan.generator}` from the "
        "requirements alone.",
        "",
        "Sources: "
        + "; ".join(f"{source.document}, {source.edition}" for source in requirements.sources)
        + ".",
        "",
    ]
    if adequacy is not None:
        mutation = adequacy.get("mutation") or {}
        invariants = adequacy["invariants"]
        decisions = adequacy["decisions"]
        lines += [
            "## Adequacy",
            "",
            f"- Accepted: **{'yes' if adequacy['accepted'] else 'no'}**",
            f"- Scenarios: {adequacy['suite']['count']} run, {adequacy['suite']['failed']} failed",
            f"- Decision coverage: {decisions.get('percent')} % "
            f"({decisions.get('outcomes_observed')} of "
            f"{decisions.get('outcomes_possible')} outcomes"
            + (f"; gaps {', '.join(decisions['gaps'])}" if decisions.get("gaps") else "")
            + ")",
            f"- Invariants: {len(invariants['invariants'])} checked on "
            f"{invariants['steps_checked']} "
            f"steps of {invariants['sequences']} randomised sequences, "
            f"{invariants['violations']} violations",
            "- Shadow Runtime vs interpreter (D3): "
            + (
                "; ".join(
                    f"{leg} leg {'agrees' if result.get('passed') else 'disagrees'} "
                    f"({result.get('policy')}, {result.get('band_set')} bands, "
                    f"{result.get('cases')} cases"
                    + (
                        f"; failing {', '.join(result.get('failing_cases', [])[:3])}"
                        if not result.get("passed")
                        else ""
                    )
                    + ")"
                    for leg, result in (adequacy.get("differential") or {}).items()
                )
                or "not run"
            ),
            "- Mutation: "
            + (
                f"{mutation['catch_rate'] * 100:.1f} % of {mutation['sample']} sampled mutants "
                f"caught (target {adequacy['mutation_target'] * 100:.0f} %)"
                if "catch_rate" in mutation
                else mutation.get("blocker", "not run")
            ),
            "",
        ]
        if adequacy["questions"]:
            lines += ["### Questions for the engineer", ""]
            lines += [f"- {question}" for question in adequacy["questions"]]
            lines.append("")
    lines += ["## Requirements and scenarios", ""]
    traced = plan.traceability()
    for requirement in requirements.requirements:
        citation = requirement.citation
        lines += [
            f"### {requirement.id} {requirement.title}",
            "",
            requirement.text,
            "",
            f"Source: {citation.document} {citation.section}"
            + (f" {citation.paragraph}" if citation.paragraph else "")
            + f" ({citation.fidelity}).",
            "",
            "Expected: "
            + "; ".join(_outcome_text(outcome) for outcome in requirement.outcomes)
            + (
                ". Otherwise: " + "; ".join(_outcome_text(o) for o in requirement.otherwise)
                if requirement.otherwise
                else ""
            )
            + ".",
            "",
            "| Scenario | Kind | Why | Result |",
            "|---|---|---|---|",
        ]
        for scenario_id in traced.get(requirement.id, []):
            scenario = plan.scenario(scenario_id)
            result = results.get(scenario.case.name)
            if result is None:
                verdict = "not run"
            elif result["passed"]:
                verdict = "pass"
            else:
                verdict = (
                    "FAIL: "
                    + "; ".join(
                        f"{f['assertion']} observed {f['observed']} expected {f['expected']}"
                        for f in result["failures"][:2]
                    )
                    + (
                        f"; {result['invariant_violations']} invariant violations"
                        if result["invariant_violations"]
                        else ""
                    )
                )
            lines.append(f"| {scenario.id} | {scenario.kind} | {scenario.rationale} | {verdict} |")
        if requirement.id not in traced:
            lines.append("| — | — | no scenario; the item is blocked | — |")
        lines.append("")
    if requirements.invariants:
        lines += ["## Invariants", ""]
        for invariant in requirements.invariants:
            when = (
                " when " + " and ".join(f"{c.point} {c.operator} {c.value}" for c in invariant.when)
                if invariant.when
                else ""
            )
            lines.append(
                f"- **{invariant.id}** {invariant.text}{when}: "
                + "; ".join(_outcome_text(outcome) for outcome in invariant.then)
                + f" ({invariant.citation.document} {invariant.citation.section})"
            )
        lines.append("")
    if plan.gaps:
        lines += ["## Gaps the test author could not close", ""]
        for gap in plan.gaps:
            lines.append(f"- {gap['requirement_id']} ({gap['kind']}): {gap['question']}")
        lines.append("")
    return "\n".join(lines)


__all__ = ["approval_digest", "render_test_plan"]
